### ISSUE TITLE
when training reward model for Llama, the source file cannot be found.

### ISSUE THREAD

**Issue by XYaoooo** [deeplearning-wisc/args#2]
16-th row in run_reward_modeling.sh
dataset_path=${project_dir}/data/hh_rlhf/rm-not-formatted/hh_rlhf_rm_data.json
There is no such path in the dataset.

**Comment by maximkha** [comment]
This should come with the LMFlow repo, I think you can find it [here](http://lmflow.org:5000/hh_rlhf.tar.gz). Specifically, it should be downloaded using the `LMFlow/data/download.sh` script. When you download it, the data should be in the `rm` subfolder.
