### ISSUE TITLE
ERROR in reward_modeling.py for training reward model of Llama

### ISSUE THREAD

**Issue by XYaoooo** [deeplearning-wisc/args#3]
<img width="841" alt="image" src="https://github.com/deeplearning-wisc/args/assets/128676980/d4a569d3-8d2b-4b43-ab24-b9d1ef431966">
It will have an assertion error.

**Comment by Top34051** [comment]
The line before the last set the `model_lora.config.pad_token_id` to `tokenizer.eos_token_id`. Both values will be the same, so the assertion will not be flagged. Please let us know if it doesn't work for you.

**Comment by Top34051** [comment]
The line before the last set the `model_lora.config.pad_token_id` to `tokenizer.eos_token_id`. Both values will be the same, so the assertion will not be flagged. Please let us know if it doesn't work for you.
